### PR TITLE
When gathering loaded/available names, allows filtering by model manager type

### PR DESCRIPTION
**Pull request by db0**
In hyper:

* Adjusted `get_loaded_models_names()` so that I can exclude or include specific model managers
* Adjusted `get_available_models_by_types()` likewise
* Created  getter `get_loaded_models()` to allow for include/excludes. 
* Created getter `get_available_models()` to allow for include/excludes
* Created `get_mm_pointers()` to convert mm enum strings, to pointers for active MMs.
* Added tests.

### CODE REVIEW

**Comment by db0** [comment]
Feel free to squash merge to fix my shitty commit messages

**Comment by tazlin** [comment]
I will handle the merge

**Comment by tazlin** [comment]
Rebased to simplify the merge.

**Review by tazlin — APPROVED** [review]
LGTM

**Pull request merged**
