### PR TITLE
Add alt pipeline design for img2img with mask

### PR DESCRIPTION
**Pull request by wolfgangmeyers**
Trying to use an alternative to VAEEncodeForInpaint when using img2img source processing and mask. Seems like SetLatentNoiseMask and VAEEncode are the answer.

Related:

https://github.com/Haidra-Org/hordelib/issues/273
https://github.com/comfyanonymous/ComfyUI/discussions/639

### CODE REVIEW

**Comment by wolfgangmeyers** [comment]
I'm a bit stuck right now, as I need to be able to convert from the pipeline design file I checked in to the version that will be used for inference. From looking at the inpainting pipeline, I don't see enough info in the design file to do the conversion. Would appreciate help on how I can create the second pipeline file for inference.

Once that's done I will update the [inference code](https://github.com/Haidra-Org/hordelib/blob/main/hordelib/horde.py#L321) and add another script in examples/ to test this out.

**Comment by tazlin** [comment]
Some comparison pictures of before the change and after may speed up the process.

**Comment by wolfgangmeyers** [comment]
Original [inpaint pipeline](https://github.com/wolfgangmeyers/hordelib/blob/main/hordelib/pipeline_designs/pipeline_stable_diffusion_paint.json):

image

Copied to new pipeline and updated to use Set Latent Noise Mask:

image

**Comment by tazlin** [comment]
@wolfgangmeyers Sorry, I wasn't very clear. Can you show the resulting images through comfyui from what the pipeline original yielded compared to the images from your change? It would be nice to have an idea of what the actual practical effect of this change is.

**Comment by wolfgangmeyers** [comment]
I based this new pipeline on the existing inpaint pipeline, so the [test](https://github.com/Haidra-Org/hordelib/pull/279/files#diff-a5f7387819ed8bc352fa7bc3c096c5f27df5a52308f2be2e841662015f064993) added in examples/ is similar as well. Here is the result of running it with denoise at 0.5:
image

**Comment by jug-dev** [comment]
This has highlighted some areas that need changing in hordelib as they've grown a bit confusing over time. I'm going to refactor and then merge this new feature.

**Pull request merged**
